// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuXI6AYlGYOWjQD2lh2JBg6lEW-qdm_AY',
    appId: '1:666394819939:ios:49f696087a6b2e97a0a756',
    messagingSenderId: '666394819939',
    projectId: 'fisher-tech',
    storageBucket: 'fisher-tech.firebasestorage.app',
    iosBundleId: 'com.example.fisherTech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuXI6AYlGYOWjQD2lh2JBg6lEW-qdm_AY',
    appId: '1:666394819939:ios:49f696087a6b2e97a0a756',
    messagingSenderId: '666394819939',
    projectId: 'fisher-tech',
    storageBucket: 'fisher-tech.firebasestorage.app',
    iosBundleId: 'com.example.fisherTech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD73NYik6InfOhAXQOK3QeCihgKbZMltw8',
    appId: '1:666394819939:web:8682cc966065a374a0a756',
    messagingSenderId: '666394819939',
    projectId: 'fisher-tech',
    authDomain: 'fisher-tech.firebaseapp.com',
    storageBucket: 'fisher-tech.firebasestorage.app',
    measurementId: 'G-X0ZCL02M75',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD73NYik6InfOhAXQOK3QeCihgKbZMltw8',
    appId: '1:666394819939:web:75ea251eef47ce7da0a756',
    messagingSenderId: '666394819939',
    projectId: 'fisher-tech',
    authDomain: 'fisher-tech.firebaseapp.com',
    storageBucket: 'fisher-tech.firebasestorage.app',
    measurementId: 'G-BR107HM1RJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAGTe2VitjuUJS_PX02bojyoK9QiJUMC8',
    appId: '1:666394819939:android:e1aad4e46bccfa54a0a756',
    messagingSenderId: '666394819939', 
    projectId: 'fisher-tech',
    storageBucket: 'fisher-tech.firebasestorage.app',
  );

}